### PR TITLE
fix: more robust generic arrow handling

### LINKED ISSUE #29: incorrect output for `return` followed by a type with a newline
**Describe the bug**
```js
function f() {
  return <T>
    (x: T)=>x;
}
```

is output as

```js
function f() {
  return    
    (x   )=>x;
}
```
which has different semantics from the input (it should match `return x => x`, but the newline after the `return` means it's parsed as `return; x => x`).

Easiest fix would be to output

```js
function f() {
  return  0,
    (x   )=>x;
}
```
or
```js

```js
function f() {
  return  (
     x   )=>x;
}
```

instead.

(Same bug occurs with `throw` and `yield` instead of `return`.)

**To Reproduce**
[playground](https://bloomberg.github.io/ts-blank-space/play/#eyJ0c3giOmZhbHNlLCJ0ZXh0IjoiZnVuY3Rpb24gZigpIHtcblx0cmV0dXJuIDxUPlxuXHRcdCh4OiBUKT0-eDtcbn1cbiJ9)

Original report: https://github.com/nodejs/node/issues/56597

### PR DESCRIPTION
**Pull request by acutmore**
**Describe your changes**

fixes #29

Given:

```ts
return<T>
(v: T) => v
```

We need to ensure the arrow function is still returned after erasing the type argument. This is achieved by moving the opening parentheses up:

```js
return(
 v: T) => v
```

**Testing performed**

Additional test fixtures have been added.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -409,15 +401,15 @@ function visitFunctionLikeDeclaration(node: ts.FunctionLikeDeclaration, kind: ts
     }
 
     let moveOpenParen = false;
+    const params = node.parameters;
     if (node.typeParameters && node.typeParameters.length) {
-        moveOpenParen = isAsync(node.modifiers) && spansLines(node.typeParameters.pos, node.typeParameters.end);
```
Comment (acutmore) [inline src/index.ts:413]: For some reason when I fixed a similar bug before I only applied the fix for `async` arrows. The `return` case hadn't occurred to me at the time.

**Comment by bakkot** [comment]
Possibly worth adding test for `throw` and `yield` as well? Obviously the current implementation makes that unnecessary but hey more tests.

**Review by robpalme — APPROVED** [review]

**Review by mkubilayk — COMMENTED** [review]
Late to the party but looks good!
